language: node_js

node_js:
  - v6

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm build

after_success:
  - npm run coverage

deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true